# Generated by Selenium IDE
from time import sleep

import pytest

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


'''
selenium IDE录制的代码：
1.代码冗余
2.还需要添加断言
'''
class TestCeshiren():
    def setup_method(self, method):
        option = Options()
        option.debugger_address = "localhost:9222"
        self.driver = webdriver.Chrome(options=option)
        #隐式等待
        self.driver.implicitly_wait(5)

    def teardown_method(self, method):
        self.driver.quit()

    def test_ceshiren(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(1440, 821)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        #断言
        '''
        1、每条测试用例必须要加入断言
        2、适当的加入一些断言在测试用例中，一般最后一个操作步骤 ，必须要加入验证点
        3、如果发生了页面的切换，通过页面标题，查找上下页面不同的元素来进行判断
        4、
        '''
        myclass = self.driver.find_element(By.LINK_TEXT, "所有分类").get_attribute("class")
        # print("myclass")
        assert 'active' == myclass
        sleep(3)